### ISSUE TITLE
db 연결에 필요한 민감한 정보 숨기기

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#11]
### Discussed in https://github.com/Cherish-Gift/back-spring/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **facewise** March 16, 2023</sup>
db 연결에 필요한 비밀번호를 git에 노출하면 안되므로 관리가 필요합니다.

spring cloud vault를 생각중입니다.</div>

**Comment by shinb-bong** [comment]
spring cloud vault 가이드 노션에 작성하였습니다.
