### ISSUE TITLE
[fix] search API 필터링 조건 situationName, gender 

### ISSUE THREAD

**Issue by lielocks** [Cherish-Gift/back-spring#122]
search API 같은 컬럼(itemfilter.name)에 대한 필터링 조건 situationName, gender 동시에 걸면 데이터 누락되는 issue

**Comment by shinb-bong** [comment]
@lielocks님  잘 적용되었는지 한번만 말씀부탁드려요!!

>현재 2번 선호 (1번은 너무 밑바닥부터 열어야함)

> 1. DB구조 변경/ 각 성별, 직업 등 상황별 분기컬럼을 넣는다.(DB구조 변경,컬럼 증가, and 검색으로 조회 속도 증가)
> 
> 2.  or 로 받아온뒤 id값을 Group By 해서 Having count ==2 인것을 뽑는다(현재 상태유지가능, 디비가 카운트 한번 계산)
> 
> 3. 기념일 한번, 아이템 한번 가지고와서 교집합을 만들어서 나온 값을 반환한다. (현재 상태 유지가능, 쿼리 두방 단점)
