### ISSUE TITLE
브랜치명 네이밍

### ISSUE THREAD

**Issue by shinb-bong** [Cherish-Gift/back-spring#13]
브랜치명 작명할때 
이슈를 해결할때
(이슈 있으면 이슈)-**영어단어** 작성이 어떨까 싶습니다. 
혹은 이슈가 없고 기능 개발시
![image](https://user-images.githubusercontent.com/81786969/225782768-0a60f27d-29cd-40a0-afe2-9e0f5215adfa.png)
해당 문서처럼 작명하는 것이 좋을 듯 합니다.

**Comment by facewise** [comment]
좋아요👍

**Comment by lielocks** [comment]
네 확인했습니다 생성된 이슈와 관련된 branch면 이슈추적 사용하고 그 뒤에 영어 워딩 이용으로 branch 작성하겠습니다!
