### ISSUE TITLE
profile 별로 다른 설정 적용

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#14]
## [https://www.baeldung.com/spring-profiles](https://www.baeldung.com/spring-profiles)

profile을 local, dev, main으로 나누어서

각 환경에 맞게 설정을 분기할 수 있도록

`application.yml`을 Multi-document 형식으로 분리합니다. [Multi-document](https://www.baeldung.com/spring-profiles#3-multi-document-files)

그리고 `DataSource`를 주입해주는 config 빈도 `@Profile` 을 추가해서 다른 설정을 사용합니다.

젠킨스에서 실행할 때 profile을 dev 또는 main으로 설정해서 실행합니다.

- [x] application.yml 내 multi-document 설정
- [x] DataSource 환경변수를 사용한 빈 추가 (local, dev 용)
- [x] Jenkins 내 실행 스크립트에 active profile 설정

**Comment by shinb-bong** [comment]
해당 기능은 사용해본적이 있는데 적용해보기 좋은 예제 같습니다!
