### ISSUE TITLE
Spring Actuator + spring boot admin 페이지

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#140]
@lielocks @shinb-bong 

지금 아직 테스트가 완료되지 않았고 테스트를 하면서 계속 서버의 로그나 상태를 확인하고

동적으로 로그레벨을 변경하는 등 작업을 위해 actuator와 spring boot admin이 잠시 있으면 좋겠다는 생각입니다

spring boot admin으로 특정 패키지나 특정 클래스의 로그 레벨을 서버가 돌아가는 중에도 동적으로 변경이 가능하거든요

Actuator는 다만 다양한 엔드포인트가 노출돼서 보안이 취약해질수 있으니 전부다 차단하고

정말 필요한 기능만 오픈하는 방식으로 해야할듯 합니다

어떻게 생각하세요?

**Comment by lielocks** [comment]
> spring boot admin으로 특정 패키지나 특정 클래스의 로그 레벨을 서버가 돌아가는 중에도 동적으로 변경이 가능하거든요

오 .. 그렇군요 !! 그럼 지금 바로 적용해도 좋을 것 같습니다 

그렇다면 여기 class에 LoggingSystem을 이용한다면
```java
@Endpoint(id = "logging")
public class LoggingEndpoint
```
management.endpoints.jmx.exposure.exclude = *
management.endpoints.web.exposure.include = info, health, logging 

이 정도만 열어놓고 사용하면 될까요 ??

**Comment by shinb-bong** [comment]
**일부 필요**한 기능만 열어놓고 사용하는 건 좋을 듯합니다!
동적으로 수정이 가능하면 보고 싶은 정보를 조절하면서 볼 수 있고 추가 모니터링 가능해서 좋을듯해요! 
actuator만으로도 로그 레벨 수정이 가능한 것으로 알고 있는데 편리하게 UI를 사용할 예정이면  spring boot admin도 좋은 것 같습니다.

**Comment by facewise** [comment]
@lielocks @shinb-bong 
네네 좋아요 봉규님은 바쁘신가요?.. 혹시 안바쁘시면 actuator랑 spring boot admin 적용 가능하신가요..ㅎㅎ

**Comment by shinb-bong** [comment]
넵 제가 담당해서 하도록 하겠습니다

**Comment by facewise** [comment]
실행을 어떻게 하셨는데요?

**Comment by facewise** [comment]
디펜던시 버전 문제입니다
