### ISSUE TITLE
[db] 추천검색어 리스트 테이블, 추천상품 목록에서 연결 검색어 키워드 컬럼

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#142]
- 추천 검색어 리스트
    - 검색창을 띄웠을때 노출되는 추천 검색어 리스트에 대한 테이블 생성

- 추천 상품 연결 검색어 키워드
    - 메인화면에서 추천 상품 목록 더보기 클릭시 연결되는 검색어 키워드 컬럼
    - 예시
        - 연결 검색 키워드
        - 목적: 기념일
        - 성별: 남성
        
        - -> 컬럼에 값을 쿼리파라미터 그대로 저장. (situationName=기념일&gender=남성)

**Comment by facewise** [comment]
@lielocks @shinb-bong 

이렇게 변경할 예정인데 한번 확인부탁드립니다

**Comment by lielocks** [comment]
네 좋습니다 !
