### ISSUE TITLE
dev, main 환경 shutdown graceful 옵션 추가

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#21]
dev나 main 환경에서는 요청을 처리하고 종료될 수 있도록 graceful shutdown 을 추가합니다

**Comment by shinb-bong** [comment]
모르는 팀원들과함께 나누기 위해

# Graceful shutdown이란
java: https://flowingmooon.tistory.com/5

Graceful shutdown은 프로그램이 종료될 때 최대한 side effect를 내지 않기 위해 로직들을 잘 처리하고 종료하는 것을 의미한다.

만약 강제로 종료된다면, 데이터의 손실과 비즈니스 로직이 제대로 처리되지 않는 채로 종료될 수 있다.

따라서, Graceful shutdown은 중요하다고 말할 수 있다.
