### ISSUE TITLE
[logging] Hibernate SQL 로그를 위한 p6spy 설정 할까요?

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#26]
p6spy를 사용하면 hibernate에서 만드는 SQL을 로그를 통해 더 확실하게 확인할수 있습니다.

근데 찾아보니까 은근히 시스템 자원을 많이 소모한다고 하더라고요

개발 및 테스트 단계에서 SQL을 보는건 좋다고 생각하는데 조금 고민이네요

어떻게 하면 좋을것 같으신가요

**Comment by shinb-bong** [comment]
개인적으로 로컬단계에서는 확인하는 것이 좋다고 생각하는 편입니다. 
fetch join 등 각 로직에 맞게 최적화를 진행했지만 원하는 결과값인지 확인을 해야하는 부분이 있으니깐요
그래서 개발 및 테스트 단계에서는 p6spy를 사용하는게 좋을듯합니다.

**Comment by facewise** [comment]
그러면 local profile 일때만 활성화 할까요?
