### ISSUE TITLE
AWS SES (이메일서버)를 통해 인증 이메일 전송

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#29]
[가이드](https://docs.aws.amazon.com/ko_kr/ses/latest/dg/send-using-smtp-programmatically.html)

이걸 확인해보고는 있는데 아마 로컬에서는 안되고 EC2에서만 메일전송 요청이 될것 같습니다.

**Comment by shinb-bong** [comment]
로컬에서는 Google 이메일
EC2 위에서는 해당 기능을 사용하는 것으로 기능을 구현하겠습니다

**Comment by shinb-bong** [comment]
로컬위에서도 작동하는 것을 확인해서 구글관련 STMP는 삭제하고
 환경변수로 key 입력하는것으로 하겠습니다.
```
    access-key: ${SES_ACCESS_KEY}
    secret-key: ${SES_SECRET_KEY}
```
KEY는 단톡방 공지사항에 있습니다
