### ISSUE TITLE
[search] 필터를 적용해서 상품 id 및 name 등 가져오기

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#55]
@lielocks 아리님이 담당해주시면 좋을것 같아요

**Comment by lielocks** [comment]
네 api 명세서에 filter 관련된 것들 작업 시작하겠습니다 !

**Comment by facewise** [comment]
완전히 혼자한다기보다는 같이 고민하면서 볼거라서요 

draft PR을 열어놓고 작업하시면 좋을것 같은데 혹시 draft PR 써본적 있으신가요?

**Comment by lielocks** [comment]
draft PR 이 일단 pr 올리고 Convert to draft 누르면 되는 건가요??

**Comment by facewise** [comment]
PR 생성할 때 
![image](https://user-images.githubusercontent.com/62998666/228705839-0e9e89f7-3c10-44b0-9b54-169d5583c4ed.png)
여기서 draft 선택하시면 됩니다

**Comment by lielocks** [comment]
아하 네 알겠습니다

**Comment by lielocks** [comment]
넵!
