### ISSUE TITLE
package명 소문자로 변경

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#6]
## package명 소문자로 변경

* [Java: Naming a Package](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

```
java 코딩 관습에 따르면 package 명은 모두 소문자로 작성하고 띄어쓰기는 하지 않습니다.

단어 별로 구분을 하지 않아도 되며 어쩔수 없이 구분이 필요할 경우 snake case로 이름을 짓습니다.

예를 들면, monthly board라는 이름의 package를 만들고 싶다면 monthlyboard로 하는 것이 java 관습이고
단어 구분이 불가피할 경우에는 monthly_board로 합니다.

```

package 이름을 변경할 때는 

- IntelliJ : shift+F6 (refactor)
- Eclipse / STS : alt+shift+V -> rename

으로 변경하면 연결된 package명이 자동으로 변경됩니다.

@Cherish-Gift/backend 
해당 이슈를 해결하실 분은 assignee에 본인을 등록하고 브랜치를 생성해주세요!!

**Comment by shinb-bong** [comment]
확인했습니당

**Comment by lielocks** [comment]
확인 완료했습니다
