### ISSUE TITLE
[bug] Controller @RequestBody에 해당하는 dto 바인딩 에러 버그

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#65]
Spring Controller 에서 `@RequestBody`에 해당하는 객체 dto가 프론트엔드에서 받아온 데이터를 정상적으로 바인딩하려면

기본 생성자 (`@NoArgsConstructor`)가 필요합니다.

[참고](https://velog.io/@conatuseus/RequestBody%EC%97%90-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC%84%B1%EC%9E%90%EB%8A%94-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80)

이 건은 PR 머지하고 나면 제가 처리하겠습니다.

**Comment by shinb-bong** [comment]
https://blogshine.tistory.com/445
