### ISSUE TITLE
package 계층 세분화

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#7]
## package 계층 세분화

* [패키지 구조 가이드](https://cheese10yun.github.io/spring-guide-directory/)

위 블로그를 한 번 읽어보시고 java에서 package를 어떻게 구조화 하면 좋을지 의견 부탁드립니다.

java 프로젝트를 처음 봤을 때 package구조부터 잘 짜여져 있으면 프로젝트가 체계적이라고 느껴집니다.

아래는 위 블로그를 참고하여 제가 생각하는 이상적인 package구조를 도식화 한 것입니다.
```
src
    ├── main
    │   ├── java
    │   │   └── io
    │   │       └── github
    │   │           └── cherishu
    │   │               ├── MainApp.java
    │   │               ├── common               // 프로젝트 전반적으로 사용할 공통
    │   │               │   ├── aop
    │   │               │   ├── config         
    │   │               │   ├── constant          
    │   │               │   ├── controller
    │   │               │   ├── dto
    │   │               │   ├── exception       // exception 이름을 정해주면 로깅 단계에서 어떤 에러 발생했는지 추적이 쉽습니다
    │   │               │   ├── model
    │   │               │   ├── repository
    │   │               │   ├── service
    │   │               │   └── util
    │   │               ├── member
    │   │               │   ├── constant          // 자주 사용하는 string 등 변수는 static final constant로 선언하고 사용
    │   │               │   ├── controller
    │   │               │   ├── dto                // front에 내려줄 json object를 객체화한 모델
    │   │               │   ├── model             // JPA entity (실제 테이블에 매핑되는 객체)
    │   │               │   ├── repository      // query dsl을 구현한 method들 포함
    │   │               │   └── service
    │   │               ├── aaaa
    │   │               │   ├── constant
    │   │               │   ├── controller
    │   │               │   ├── dto
    │   │               │   ├── model
    │   │               │   ├── repository
    │   │               │   └── service
    │   │               └── bbbb
    │   │                   ├── constant
    │   │                   ├── controller
    │   │                   ├── dto
    │   │                   ├── model
    │   │                   ├── repository
    │   │                   └── service
    │   └── resources
    │       └── application.yml

```

이 이슈는 #6 6 이 먼저 해결되고 나면 진행할 예정입니다

**Comment by shinb-bong** [comment]
application은 요즘 yml을 쓰는 추세이니 yml을 사용하는 것이 좋을듯하고 
공통 부분은 합치는게 좋을 것 같습니다! 
저는 평소 config는 상위로 올렸는데 공통부분이니 해당 디렉터리 구조도 좋은 것 같습니다.

**Comment by facewise** [comment]
> application은 요즘 yml을 쓰는 추세이니 yml을 사용하는 것이 좋을듯하고 공통 부분은 합치는게 좋을 것 같습니다! 저는 평소 config는 상위로 올렸는데 공통부분이니 해당 디렉터리 구조도 좋은 것 같습니다.

생각해보니까 config를 common과 같은레벨인 상위 레벨로 올리는 것도 좋은것 같아요.

다만 혹시나 나중에 기능별로 config가 생길수 있어서 (e.g. member.config) 

그럴땐 프로젝트 전체 환경설정을 common 밑으로 넣는건 어떨까 싶습니다

**Comment by shinb-bong** [comment]
@facewise 
그것도 좋은 방법인 것 같아요 
설정파일이라 실행 클래스와 가까운 곳에 위치시키려고 한것일뿐 공통 기능이여서 common 안으로 가도될 것 같아요!
요점은 config를 모아서 관리하는데 기능별로 생기면 config 디렉토리안에서 해당 디렉토리를 나눠서  관리하는 것이 좋을 듯합니다!

**Comment by lielocks** [comment]
해당 이슈를 지금 확인하였습니다! 
저는 단순 계층형 구조를 생각했었는데 용현님이 제안해주신 기능별로 그룹화된 package구조도 체계적으로 계층화할 수 있어 좋은 것 같습니다 
security 관련 설정은 common과 분리하는여 따로 패키지를 만드는게 맞을까요?

**Comment by facewise** [comment]
> 해당 이슈를 지금 확인하였습니다! 
> 저는 단순 계층형 구조를 생각했었는데 용현님이 제안해주신 기능별로 그룹화된 package구조도 체계적으로 계층화할 수 있어 좋은 것 같습니다 
> security 관련 설정은 common과 분리하여 따로 패키지를 만드는게 맞을까요?

네 뭐 security 따로 빼는것도 명시적이고 괜찮을것 같아요
