### ISSUE TITLE
[refactor] 회원가입시 이메일 인증 여부 확인

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/back-spring#72]
### 예시

- 회원가입시 인증 이메일을 보내면 아래와 같이 key, value를 세팅한다.

```JSON
"foo@bar.com": {
  "code": "023514",
  "verified": false
}
```

- 유저가 이메일 인증번호를 입력해서 성공하면 verified를 true로 바꾼다.
- 회원가입 api를 받으면 해당 이메일로 Redis에서 verified가 true인지 체크한다.

이외에도 다른 좋은 방법이 있으시면 의견 부탁드립니다.
@lielocks @shinb-bong

**Comment by lielocks** [comment]
아 인증 여부를 value로 넣어서 관리하면 검색도 빠르고 좋을 것 같습니다 !
