### ISSUE TITLE
[feature] 상품 상세정보 api 설계

### ISSUE THREAD

**Issue by lielocks** [Cherish-Gift/back-spring#92]
views 증가는 redis를 활용해서 처리해주도록 하겠습니다 !

**Comment by facewise** [comment]
redis를 어떻게 활용하실 생각이신가요?

**Comment by lielocks** [comment]
api 호출될때마다 db에 views를 +1하는것보다 redis에 views 밸류값을 +1시키는게 좋지 않을까 해서 활용할 생각이었습니다 !

**Comment by facewise** [comment]
아하 넵. 일단은 그렇게 진행하시는데 저희 레디스가 지금 프리티어로 500MB용량이어서 나중에 메모리 부족해지면
db 기반으로 변경할 수도 있습니다.

이건 레디스 사용하고 있는 리프레쉬토큰도 마찬가지입니다.

그리고 메모리 기반이어서 인스턴스 장애가 생기면 데이터가 유실될 수도 있을것 같아요

**Comment by lielocks** [comment]
아 네네 알겠습니다 !
