### ISSUE TITLE
[refactor] 상품 상세정보 조회 api

### ISSUE THREAD

**Issue by lielocks** [Cherish-Gift/back-spring#97]
해당 api에서 호출되는 sql문이 너무 많아 리팩토링 작업 진행하겠습니다 
draft 로 열어두고 계속 commit하면서 진행하겠습니다

**Comment by shinb-bong** [comment]
draft 지켜보면서 저도 브랜치 하나 해서 테스트를 해볼까하니 `test`가 들어간 네이밍 브랜치 하나 만들 수도 있습니당
